<#-- @ftlvariable name="link" type="String" -->
<#assign
    mailTitle = "Passwort zurücksetzen"
    brandName = "Movio"
    headerTitle = "Passwort zurücksetzen"
    headerSubtitle = "Ein sicherer Link, um den Zugriff auf Ihr Konto wiederherzustellen."
    companyName = "Movio"
    companySite = "movio.com.ua"
    year = "2026"
    contentTemplate = "/content/reset_password_content.ftlh"
/>
<#include "/layouts/base_mail.ftlh">