spring:
  application:
    name: Task Tracker
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:movio_web_main}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false # Вимкнули Flyway згідно з вашим запитом
    locations: classpath:db/migration
  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

confirmation:
  expiration:
    days: ${CONFIRMATION_EXPIRATION_DAYS:5}

app:
  base-url: ${BASE_URL:http://localhost:8080}
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

digitalocean:
  spaces:
    access-key: ${DO_SPACES_ACCESS_KEY}
    secret-key: ${DO_SPACES_SECRET_KEY}
    endpoint: ${DO_SPACES_ENDPOINT:https://fra1.digitaloceanspaces.com}
    region: ${DO_SPACES_REGION:fra1}
    bucket-name: ${DO_SPACES_BUCKET:test-bucket}


#1 day = 1440min
#7 day = 10080min
jwt:
  at:
    live-in-min: ${JWT_AT_LIVE_IN_MIN}
    secret: ${JWT_AT_SECRET}
  rt:
    live-in-min: ${JWT_RT_LIVE_IN_MIN}
    secret: ${JWT_RT_SECRET}

springdoc:
  swagger-ui:
    with-credentials: true
